spring.application.name=planeo-auth
--spring.profiles.active=dev
server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
jwt.secret=votre_secret_tres_long_au_moins_256_bits_pour_hs256
jwt.expiration=86400000
jwt.refresh-expiration=604800000